export const galleryItems = [
  {
    id: 1,
    title: 'Minimalist Living Room',
    image: 'https://images.pexels.com/photos/1080696/pexels-photo-1080696.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Living Room',
    style: 'Modern',
    tags: ['Minimalist', 'Contemporary', 'Neutral Colors'],
    decorator: 'Sarah Johnson',
    price: '$3,500',
    additionalImages: [
      'https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
  },
  {
    id: 2,
    title: 'Cozy Bedroom Design',
    image: 'https://images.pexels.com/photos/1743229/pexels-photo-1743229.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Bedroom',
    style: 'Scandinavian',
    tags: ['Cozy', 'Scandinavian', 'Wood Elements'],
    decorator: 'Emma Davis',
    price: '$2,800',
    additionalImages: [
      'https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/462235/pexels-photo-462235.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
  },
  {
    id: 3,
    title: 'Contemporary Kitchen',
    image: 'https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Kitchen',
    style: 'Contemporary',
    tags: ['Contemporary', 'Open Plan', 'Island'],
    decorator: 'Michael Chen',
    price: '$6,200',
    additionalImages: [
      'https://images.pexels.com/photos/373548/pexels-photo-373548.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/534151/pexels-photo-534151.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
  },
  {
    id: 4,
    title: 'Luxury Bathroom',
    image: 'https://images.pexels.com/photos/1571470/pexels-photo-1571470.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Bathroom',
    style: 'Luxury',
    tags: ['Luxury', 'Marble', 'Spa-like'],
    decorator: 'Sarah Johnson',
    price: '$4,100',
    additionalImages: [
      'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
  },
  {
    id: 5,
    title: 'Industrial Office',
    image: 'https://images.pexels.com/photos/1571463/pexels-photo-1571463.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Office',
    style: 'Industrial',
    tags: ['Industrial', 'Exposed Brick', 'Metal'],
    decorator: 'Michael Chen',
    price: '$3,900',
    additionalImages: [
      'https://images.pexels.com/photos/296883/pexels-photo-296883.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/210265/pexels-photo-210265.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
  },
  {
    id: 6,
    title: 'Rustic Dining Room',
    image: 'https://images.pexels.com/photos/1080696/pexels-photo-1080696.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Dining Room',
    style: 'Rustic',
    tags: ['Rustic', 'Farmhouse', 'Natural Wood'],
    decorator: 'Emma Davis',
    price: '$2,600',
    additionalImages: [
      'https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/210604/pexels-photo-210604.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
  },
  {
    id: 7,
    title: 'Modern Balcony',
    image: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Balcony',
    style: 'Modern',
    tags: ['Modern', 'Outdoor', 'Plants'],
    decorator: 'Sarah Johnson',
    price: '$1,800',
    additionalImages: [
      'https://images.pexels.com/photos/1428347/pexels-photo-1428347.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1230677/pexels-photo-1230677.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
  },
  {
    id: 8,
    title: 'Classic Study Room',
    image: 'https://images.pexels.com/photos/1743229/pexels-photo-1743229.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Study',
    style: 'Classic',
    tags: ['Classic', 'Library', 'Dark Wood'],
    decorator: 'Michael Chen',
    price: '$3,200',
    additionalImages: [
      'https://images.pexels.com/photos/207697/pexels-photo-207697.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/256401/pexels-photo-256401.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
  },
  {
    id: 9,
    title: 'Bohemian Living Space',
    image: 'https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Living Room',
    style: 'Bohemian',
    tags: ['Bohemian', 'Colorful', 'Textiles'],
    decorator: 'Emma Davis',
    price: '$2,900',
    additionalImages: [
      'https://images.pexels.com/photos/462118/pexels-photo-462118.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/105003/pexels-photo-105003.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
  },
  {
    id: 10,
    title: 'Art Deco Bedroom',
    image: 'https://images.pexels.com/photos/1571470/pexels-photo-1571470.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Bedroom',
    style: 'Art Deco',
    tags: ['Art Deco', 'Glamorous', 'Gold Accents'],
    decorator: 'Sarah Johnson',
    price: '$4,500',
    additionalImages: [
      'https://images.pexels.com/photos/1571458/pexels-photo-1571458.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1571459/pexels-photo-1571459.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
  },
  {
    id: 11,
    title: 'Zen Meditation Room',
    image: 'https://images.pexels.com/photos/1571463/pexels-photo-1571463.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Meditation',
    style: 'Zen',
    tags: ['Zen', 'Peaceful', 'Natural Light'],
    decorator: 'Emma Davis',
    price: '$2,100',
    additionalImages: [
      'https://images.pexels.com/photos/105028/pexels-photo-105028.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/105029/pexels-photo-105029.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
  },
  {
    id: 12,
    title: 'Victorian Kitchen',
    image: 'https://images.pexels.com/photos/1080696/pexels-photo-1080696.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Kitchen',
    style: 'Victorian',
    tags: ['Victorian', 'Ornate', 'Traditional'],
    decorator: 'Michael Chen',
    price: '$5,800',
    additionalImages: [
      'https://images.pexels.com/photos/534151/pexels-photo-534151.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/210604/pexels-photo-210604.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
  },
  // Additional new gallery items
  {
    id: 13,
    title: 'Urban Loft Workspace',
    image: 'https://images.pexels.com/photos/380768/pexels-photo-380768.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Office',
    style: 'Urban',
    tags: ['Urban', 'Loft', 'Open Space'],
    decorator: 'Lucas Brown',
    price: '$4,700',
    additionalImages: [
      'https://images.pexels.com/photos/373548/pexels-photo-373548.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/256401/pexels-photo-256401.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
  },
  {
    id: 14,
    title: 'Elegant Dining Area',
    image: 'https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Dining Room',
    style: 'Elegant',
    tags: ['Elegant', 'Chic', 'Bright'],
    decorator: 'Mia Kim',
    price: '$3,300',
    additionalImages: [
      'https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/534151/pexels-photo-534151.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
  },
];